import { createFileRoute } from '@tanstack/react-router'
import { useCallback } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { addDataset } from '@/stores/datasets'

export const Route = createFileRoute('/')({ 
  component: RouteComponent,
})

function RouteComponent() {
  const navigate = useNavigate()

  const handleFileUpload = useCallback(async (file: File) => {
    await addDataset(file)
    navigate({ to: '/datasets/$id', params: { id: file.name } })
  }, [navigate])

  return (
    <>
      <header className="border-b">
        <div className="container">
          <h1 className="text-3xl font-bold">Welcome to Datalytics</h1>
          <p className="mt-2 text-sm text-muted-foreground">AI-Powered Data Analytics Platform</p>
        </div>
      </header>

      <main className="container py-6">
        <div className="rounded-lg border bg-card p-6 shadow-sm">
          <div className="space-y-4">
            <h2 className="text-lg font-medium">Getting Started</h2>
            <p className="text-muted-foreground">Upload your dataset to begin analyzing your data.</p>
            
            <div
              className="border-2 border-dashed rounded-lg p-12 text-center hover:bg-accent/50 transition-colors cursor-pointer"
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => {
                e.preventDefault()
                const file = e.dataTransfer.files[0]
                if (file) handleFileUpload(file)
              }}
              onClick={() => {
                const input = document.createElement('input')
                input.type = 'file'
                input.accept = '.csv,.json,.txt'
                input.onchange = (e) => {
                  const file = (e.target as HTMLInputElement).files?.[0]
                  if (file) handleFileUpload(file)
                }
                input.click()
              }}
            >
              <div className="text-muted-foreground">
                <p>Drag and drop your dataset here</p>
                <p className="text-sm">or click to browse</p>
                <p className="text-xs mt-2">.csv, .json, .txt files supported</p>
              </div>
            </div>

            <div className="mt-6">
              <p className="text-muted-foreground">Once uploaded, you can:</p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                <li>View dataset insights automatically generated by AI</li>
                <li>Create custom analyses by asking questions about your data</li>
                <li>Access previous analyses and datasets from the sidebar</li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}