import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')({
  component: RouteComponent,
})

function RouteComponent() {
  return (
    <>
      <header className="border-b">
        <div className="container">
          <h1 className="text-3xl font-bold">Welcome to Datalytics</h1>
          <p className="mt-2 text-sm text-muted-foreground">AI-Powered Data Analytics Platform</p>
        </div>
      </header>

      <main className="container py-6">
        <div className="rounded-lg border bg-card p-6 shadow-sm">
          <div className="space-y-4">
            <h2 className="text-lg font-medium">Getting Started</h2>
            <p className="text-muted-foreground">Upload a dataset from the sidebar to begin analyzing your data.</p>
            <p className="text-muted-foreground">Once uploaded, you can:</p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
              <li>View dataset insights automatically generated by AI</li>
              <li>Create custom analyses by asking questions about your data</li>
              <li>Access previous analyses and datasets from the sidebar</li>
            </ul>
          </div>
        </div>
      </main>
    </>
  )
}