/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DatasetsIdImport } from './routes/datasets.$id'
import { Route as AnalysesIdImport } from './routes/analyses.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DatasetsIdRoute = DatasetsIdImport.update({
  id: '/datasets/$id',
  path: '/datasets/$id',
  getParentRoute: () => rootRoute,
} as any)

const AnalysesIdRoute = AnalysesIdImport.update({
  id: '/analyses/$id',
  path: '/analyses/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/analyses/$id': {
      id: '/analyses/$id'
      path: '/analyses/$id'
      fullPath: '/analyses/$id'
      preLoaderRoute: typeof AnalysesIdImport
      parentRoute: typeof rootRoute
    }
    '/datasets/$id': {
      id: '/datasets/$id'
      path: '/datasets/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof DatasetsIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/datasets/$id': typeof DatasetsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/datasets/$id': typeof DatasetsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/datasets/$id': typeof DatasetsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyses/$id' | '/datasets/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyses/$id' | '/datasets/$id'
  id: '__root__' | '/' | '/analyses/$id' | '/datasets/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesIdRoute: typeof AnalysesIdRoute
  DatasetsIdRoute: typeof DatasetsIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesIdRoute: AnalysesIdRoute,
  DatasetsIdRoute: DatasetsIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/analyses/$id",
        "/datasets/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/analyses/$id": {
      "filePath": "analyses.$id.tsx"
    },
    "/datasets/$id": {
      "filePath": "datasets.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
